//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailSender.ConsoleTest2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Length { get; set; }
    
        public virtual Artist Artist { get; set; }
    }
}
